// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Showcase.Infrastructure.Persistence.Database;

#nullable disable

namespace Showcase.Infrastructure.Persistence.Database.Migrations
{
    [DbContext(typeof(MeasurementDbContext))]
    [Migration("20220726101220_AddCoordinates")]
    partial class AddCoordinates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Showcase.Domain.Measurements.Temperatures.Temperature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Temperatures");
                });

            modelBuilder.Entity("Showcase.Domain.Measurements.Temperatures.Temperature", b =>
                {
                    b.OwnsOne("Showcase.Domain.Measurements.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("TemperatureId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");

                            b1.HasKey("TemperatureId");

                            b1.ToTable("Temperatures");

                            b1.WithOwner()
                                .HasForeignKey("TemperatureId");
                        });

                    b.Navigation("Coordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
